name: SimpleDialog
version: ${version}
main: com.github.sahyuya.simpleDialog.SimpleDialog
api-version: '1.21'
description: A plugin to show welcome dialogs for new players
softdepend:
  - GeyserMC
  - Floodgate
  - DynamicProfile

permissions:
  simpledialog.admin:
    description: Allows access to admin commands
    default: op